Blog App - processing data in models
GraceHtet/blog_rails pull request #2
Opened 2023-06-07 16:06 UTC by GraceHtet

- Create model classes for all entities as shown in the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png).

- Set up associations between models.

- Created custom methods

- Users

> A method that returns the 3 most recent posts for a given user.

- Posts

> A method that updates the posts counter for a user.
> A method which returns the 5 most recent comments for a given post.

- Comments

> A method that updates the comments counter for a post.

- Likes

> A method that updates the likes counter for a post.

2023-06-07 17:06 UTC, Munsa1 requested changes
Hi @GraceHtet, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Created All Models :heavy_check_mark: 
Created All Methods Inside The Models :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 
Good Commit Messages :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Due to insufficient files changed I will leave comment here
- [ ] Kindly remove the `Run Tests` and `Deployment` links in the table of contents of your ReadMe file as these links lead nowhere and as such are broken links.
![image](https://github.com/GraceHtet/blog_rails/assets/81932478/195621a2-20ec-4f04-997b-ce0b22538993)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 17:06 UTC, Munsa1 commented on app/models/post.rb
> +  end
- [ ] It would be nice to use one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - after_save to call the #post_counter_update method every time a new post has been saved to database, Kindly implement this:

e.g
` after_save :post_counter_update`

2023-06-07 17:06 UTC, Munsa1 commented on app/models/comment.rb
> +
- [ ] Just like we have in the `post` model, here as well it would be nice to have a `Rails Active Callback` that calls the #comment_counter_update method every time a new comment is saved to the database. Kindly implement this requirement

2023-06-07 17:06 UTC, Munsa1 commented on app/models/like.rb
> +
- [ ] Just like we have in the `comment` model, here as well it would be nice to have a `Rails Active Callback` that calls the #like_counter_update method every time a new comment is saved to the database. Kindly implement this requirement as well

2023-06-08 02:29 UTC, DuaneDave approved these changes
Hi @GraceHtet 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Relationships are correctly set up
✔️ All methods are well implemented

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 02:37 UTC, merged